export const POPULATE_LIST_OF_TOP_MOVIES = 'POPULATE_LIST_OF_TOP_MOVIES';
export const ADD_MOVIE_TO_FAVORITES = 'ADD_MOVIE_TO_FAVORITES';
export const REMOVE_MOVIE_FROM_FAVORITES = 'REMOVE_MOVIE_FROM_FAVORITES';